# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iiRV7EzJnEsNz--T3Bn8ujmaDQoQiBK
"""

import os
import urllib.request
import pandas as pd

# Create folders
os.makedirs("/content/data/diabetes", exist_ok=True)
os.makedirs("/content/data/cardio", exist_ok=True)


# ============================================================
# 1. PIMA INDIANS DIABETES DATASET
# ============================================================

diabetes_url = (
    "https://raw.githubusercontent.com/jbrownlee/Datasets/master/"
    "pima-indians-diabetes.data.csv"
)

diabetes_file = "/content/data/diabetes/diabetes.csv"

print("Downloading Diabetes dataset...")

urllib.request.urlretrieve(
    diabetes_url,
    diabetes_file
)

diabetes_columns = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

df_diabetes = pd.read_csv(
    diabetes_file,
    header=None,
    names=diabetes_columns
)

df_diabetes.to_csv(
    diabetes_file,
    index=False
)

print("✓ Diabetes downloaded")
print("Path:", diabetes_file)
print("Shape:", df_diabetes.shape)


# ============================================================
# 2. UCI CLEVELAND HEART DISEASE DATASET
# ============================================================

heart_url = (
    "https://archive.ics.uci.edu/ml/"
    "machine-learning-databases/heart-disease/"
    "processed.cleveland.data"
)

heart_file = "/content/data/cardio/heartDisease_uci.csv"

print("\nDownloading UCI Heart Disease dataset...")

heart_columns = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "target"
]

heart_raw = "/content/data/cardio/processed.cleveland.data"

urllib.request.urlretrieve(
    heart_url,
    heart_raw
)

df_heart = pd.read_csv(
    heart_raw,
    header=None,
    names=heart_columns,
    na_values="?"
)

# Convert target:
# 0 = No heart disease
# 1 = Heart disease
df_heart["target"] = (
    df_heart["target"] > 0
).astype(int)

df_heart.to_csv(
    heart_file,
    index=False
)

print("✓ Heart Disease downloaded")
print("Path:", heart_file)
print("Shape:", df_heart.shape)


# ============================================================
# 3. VERIFY
# ============================================================

print("\n" + "=" * 60)
print("DATASETS READY")
print("=" * 60)

print("\nDiabetes:")
print(df_diabetes.shape)
display(df_diabetes.head())

print("\nHeart Disease:")
print(df_heart.shape)
display(df_heart.head())

print("\nFiles:")
print(diabetes_file)
print(heart_file)

import pandas as pd
import numpy as np

# ---- Load ----
diabetes_df = pd.read_csv("data/diabetes/diabetes.csv")
cardio_df = pd.read_csv("/content/data/cardio/heartDisease_uci.csv")

# ---- Clean Diabetes Data ----
# Zero values in these columns are actually missing data
zero_as_missing = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
for col in zero_as_missing:
    diabetes_df[col] = diabetes_df[col].replace(0, np.nan)
    diabetes_df[col] = diabetes_df[col].fillna(diabetes_df[col].median())

print("Diabetes shape:", diabetes_df.shape)
print(diabetes_df.isnull().sum())

# ---- Clean Cardio Data ----
cardio_df = cardio_df.dropna()
print("Cardio shape:", cardio_df.shape)
print(cardio_df.head())

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score
import joblib
import os

# Create models folder
os.makedirs("models", exist_ok=True)


def train_and_evaluate(df, target_col, model_name):

    print(f"\nTraining {model_name}...")

    # Check target column
    if target_col not in df.columns:
        print("Available columns:")
        print(df.columns.tolist())
        raise ValueError(
            f"Target column '{target_col}' not found in dataframe."
        )

    # Separate features and target
    X = df.drop(columns=[target_col])
    y = df[target_col]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # XGBoost model
    model = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        eval_metric="logloss",
        random_state=42
    )

    # Train
    model.fit(X_train, y_train)

    # Predictions
    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:, 1]

    # Metrics
    accuracy = accuracy_score(y_test, preds)
    roc_auc = roc_auc_score(y_test, probs)
    f1 = f1_score(y_test, preds)

    print(f"\n--- {model_name} ---")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"ROC-AUC : {roc_auc:.4f}")
    print(f"F1-score: {f1:.4f}")

    # Save model
    model_path = f"models/{model_name}.pkl"
    joblib.dump(model, model_path)

    print(f"Model saved: {model_path}")

    # Return model + feature names
    return model, X_train.columns.tolist()


# ============================================================
# DIABETES MODEL
# ============================================================

diabetes_model, diabetes_features = train_and_evaluate(
    diabetes_df,
    "Outcome",
    "diabetes_model"
)


# ============================================================
# HEART DISEASE MODEL
# ============================================================

cardio_model, cardio_features = train_and_evaluate(
    cardio_df,
    "target",             # IMPORTANT: not "condition"
    "cardio_model"
)


# ============================================================
# SAVE FEATURE LISTS
# ============================================================

joblib.dump(
    diabetes_features,
    "models/diabetes_features.pkl"
)

joblib.dump(
    cardio_features,
    "models/cardio_features.pkl"
)

print("\n" + "=" * 60)
print("TRAINING COMPLETED SUCCESSFULLY")
print("=" * 60)

print("\nDiabetes features:")
print(diabetes_features)

print("\nHeart disease features:")
print(cardio_features)

print("\nSaved files:")
print("models/diabetes_model.pkl")
print("models/cardio_model.pkl")
print("models/diabetes_features.pkl")
print("models/cardio_features.pkl")

import shap

def explain_prediction(model, feature_names, input_row):
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(input_row)

    # Handle both single-array and list output formats
    values = shap_values[0] if isinstance(shap_values, list) else shap_values[0]

    contributions = sorted(
        zip(feature_names, values), key=lambda x: abs(x[1]), reverse=True
    )
    top_factors = [{"feature": f, "impact": round(float(v), 3)} for f, v in contributions[:5]]
    return top_factors

# Example usage:
# sample = X_test.iloc[[0]]
# explain_prediction(diabetes_model, diabetes_features, sample)

!apt-get install -y tesseract-ocr -q
!pip install pytesseract pillow -q

import pytesseract
from PIL import Image
import re

def extract_report_values(image_path):
    text = pytesseract.image_to_string(Image.open(image_path))

    patterns = {
        "Glucose": r"glucose[:\s]+(\d+\.?\d*)",
        "BloodPressure": r"(?:blood pressure|bp)[:\s]+(\d+)",
        "Cholesterol": r"cholesterol[:\s]+(\d+\.?\d*)",
        "BMI": r"bmi[:\s]+(\d+\.?\d*)",
    }

    extracted = {}
    text_lower = text.lower()
    for key, pattern in patterns.items():
        match = re.search(pattern, text_lower)
        if match:
            extracted[key] = float(match.group(1))

    return extracted, text

SYMPTOM_KEYWORDS = {
    "frequent urination": {"Glucose": +15},
    "excessive thirst": {"Glucose": +10},
    "fatigue": {"Glucose": +5, "BMI": +2},
    "blurred vision": {"Glucose": +10},
    "chest pain": {"trestbps": +10, "thalach": -5},
    "shortness of breath": {"thalach": -10},
    "dizziness": {"trestbps": +5},
    "high blood pressure": {"trestbps": +15},
}

def parse_symptoms(text):
    text = text.lower()
    detected = {}
    for symptom, adjustments in SYMPTOM_KEYWORDS.items():
        if symptom in text:
            for feature, delta in adjustments.items():
                detected[feature] = detected.get(feature, 0) + delta
    return detected

def fuse_features(base_features: dict, symptom_adjustments: dict, ocr_values: dict):
    """
    base_features: manual form input (dict of all required model features)
    symptom_adjustments: output of parse_symptoms()
    ocr_values: output of extract_report_values()
    """
    final = dict(base_features)

    # OCR values override manual input if present
    for k, v in ocr_values.items():
        if k in final:
            final[k] = v

    # Symptom adjustments nudge the values slightly
    for k, delta in symptom_adjustments.items():
        if k in final:
            final[k] += delta

    return final